name: Test Container Scans

on:
  workflow_dispatch:
    inputs:
      api:
        description: "Enter the target Endor Labs API"
        required: true
        type: choice
        default: https://api.endorlabs.com
        options:
        - https://api.staging.endorlabs.com
        - https://api.endorlabs.com
      tenant_name:
        description: "Enter your Endor Labs namespace?"
        required: true
        type: string

jobs:
  release:
    name: Build and Sign
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build JAR
        run: mvn clean install -Dskiptests=true

      
      - name: Endor Labs Scan
        uses: endorlabs/github-action@main
        with:
          namespace: ${{ github.event.inputs.tenant_name }}
          api: ${{ github.event.inputs.api }}
          scan_summary_output_type: "table"
          pr: "false"
          enable_github_action_token: "true"
          scan_dependencies: "true"
          scan_secrets: "true"
          scan_git_logs: "true"

      - name: Create container
        run: docker build -t app-java-demo:latest .

      - name: Endor Labs Scan
        uses: endorlabs/github-action@main
        with:
          namespace: ${{ github.event.inputs.tenant_name }}
          api: ${{ github.event.inputs.api }}
          scan_summary_output_type: "table"
          pr: "false"
          enable_github_action_token: "true"
          scan_dependencies: "false"
          scan_container: "true"
          image: "app-java-demo:latest"
