name: Endor Labs PR SAST Check
on:
  pull_request:
    branches: [ new_main]
  workflow_dispatch:
jobs:
  scan:
    permissions:
      security-events: write 
      contents: read 
      id-token: write 
      issues: write # Required to automatically comment on PRs for new policy violations
      pull-requests: write # Required to automatically comment on PRs for new policy violations
      actions: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install semgrep==1.99.0
    - name: Endor Labs Scan Pull Request
      uses: endorlabs/github-action@v1
      with:
        namespace: 'nate-learn'
        scan_dependencies: false
        scan_sast: true
        pr: true
        enable_pr_comments: true
        github_token: ${{ secrets.GITHUB_TOKEN }} # Required for PR comments on new policy violations
