name: Endor Labs Scan Performance Benchmark New Version
on:
  workflow_dispatch:
    inputs:
      api:
        description: "Enter the target Endor Labs API"
        required: true
        type: choice
        default: https://api.endorlabs.com
        options:
        - https://api.staging.endorlabs.com
        - https://api.endorlabs.com
      tenant_name:
        description: "Enter your Endor Labs namespace?"
        required: true
        type: string
jobs:
  app-java-demo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
        - uses: actions/checkout@v3
          with:
            repository: endorlabs/app-java-demo
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: microsoft
            java-version: "17"
        - name: Compile Package
          run: mvn clean install
        - name: Setup Endor Endor Labs
          run: |
            curl https://api.staging.endorlabs.com/download/endorlabs/v1.7.385/binaries/endorctl_v1.7.385_linux_amd64 -o endorctl;
            echo "eb06778c22aa893567f4133d680c84ad852ddc70ab7714c281367a5c7e4b5af8 endorctl" | sha256sum --check;
            chmod +x ./endorctl
        - name: Endor Labs Scan - Full Scan
          env:
            ENDOR_NAMESPACE: "${{ github.event.inputs.tenant_name }}"
            ENDOR_API: "${{ github.event.inputs.api_base }}"
            ENDOR_API_CREDENTIALS_KEY: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
            ENDOR_API_CREDENTIALS_SECRET: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          run: ./endorctl scan
        - name: Endor Labs Scan - Quick Scan
          env:
            ENDOR_NAMESPACE: "${{ github.event.inputs.tenant_name }}"
            ENDOR_API: "${{ github.event.inputs.api_base }}"
            ENDOR_API_CREDENTIALS_KEY: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
            ENDOR_API_CREDENTIALS_SECRET: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          run: ./endorctl scan --quick-scan
        - name: Download Snyk
          uses: snyk/actions/setup@master
        - name: Run Snyk Dev Deps
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          run: snyk test --all-projects --dev
        - name: Run Snyk No Dev Deps
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          run: snyk test --all-projects 
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.9"
        - name: Download Semgrep Supply Chain
          env:
          # Connect to Semgrep AppSec Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep AppSec Platform > Settings
          # and add it to your GitHub secrets.
            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          run: |
            python3 -m pip install semgrep
        - name: Run Semgrep
          env:
          # Connect to Semgrep AppSec Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep AppSec Platform > Settings
          # and add it to your GitHub secrets.
            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          run: semgrep ci --supply-chain 
