name: SAST Scanning Test
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: |
          Enter the namespace . Default: demo
        required: false
        type: string
        default: 'demo'
      api:
        description: 'Environment to run the tests on'
        required: true
        default: 'https://api.staging.endorlabs.com'
        type: choice
        options:
        - https://api.staging.endorlabs.com
        - https://api.endorlabs.com

jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup namespace Environment Variables
        run: |
            NAMESPACE=$(jq -r '.inputs.tenant_name' $GITHUB_EVENT_PATH)
            echo "::add-mask::$NAMESPACE"
            echo NAMESPACE=$NAMESPACE >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Ensure you use a valid Python version

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Semgrep version
        run: |
          semgrep --version

      - name: Endor Labs SAST Code Scan
        uses: endorlabs/github-action@main
        with:
            namespace: ${{ inputs.namespace }}
            api: ${{ inputs.api }}
            scan_summary_output_type: "table"
            pr: "false"
            enable_github_action_token: "true"
            scan_sast: "true"
            scan_dependencies: "false"
